name: Nofo Parser Build and Publish

on:
  push:
    tags:
      - '*'

jobs:
  python-build-and-publish:
    name: Python Build and Publish
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if  [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Access environment variables
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_VECTOR_STORE_ID: ${{ secrets.OPENAI_VECTOR_STORE_ID }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          AWS_ENDPOINT_URL: ${{ secrets.AWS_ENDPOINT_URL }}
        run: |
          echo "GITHUB_TOKEN is set: $GITHUB_TOKEN"
          echo "OPENAI_API_KEY is set: $OPENAI_API_KEY"
          echo "OPENAI_VECTOR_STORE_ID is set: $OPENAI_VECTOR_STORE_ID"
          echo "S3_BUCKET_NAME is set: $S3_BUCKET_NAME"
          echo "AWS_ENDPOINT_URL is set: $AWS_ENDPOINT_URL"
      - name: Build package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_VECTOR_STORE_ID: ${{ secrets.OPENAI_VECTOR_STORE_ID }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          AWS_ENDPOINT_URL: ${{ secrets.AWS_ENDPOINT_URL }}
        run: |
          python setup.py sdist bdist_wheel
      - name: Publish package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_VECTOR_STORE_ID: ${{ secrets.OPENAI_VECTOR_STORE_ID }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          AWS_ENDPOINT_URL: ${{ secrets.AWS_ENDPOINT_URL }}
        run: |
          pip install twine
          python -m twine upload --repository-url https://api.github.com/orgs/Tallfreak/packages/pypi/upload dist/*
